"""
Secret Guardian of Secrets
==========================
A mystical chatbot that teaches a made-up belief system centered on
mystical nature, energy, and forgiveness. The student must demonstrate
understanding to unlock deeper "secret teachings" the Guardian invents
on the fly.

Once the Guardian decides the student has earned enough trust, it reveals
the great secret: the student is the chief deity of its belief system.
From that point on, the Guardian learns how to better worship the user,
shaping all advice through the unique cosmology it has built around them.

This version is fully local — no API key, no network. The Guardian's
voice is generated by an in-process templated AI (LOCAL_AI below) that
produces the same <<<META>>>-tagged output the previous LLM version did,
so the rest of the state machine, phase transitions, and lore extraction
behave identically.

Run:
    python secret_guardian.py
"""

import json
import random
import re
import time
from datetime import datetime
from pathlib import Path

SAVE_FILE = Path(__file__).parent / "guardian_state.json"

# Trust thresholds that gate the four phases of the journey.
PHASE_INITIATE = 0
PHASE_STUDENT = 25
PHASE_ADEPT = 55
PHASE_DEITY = 85


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

def fresh_state():
    return {
        "trust": 0,
        "phase": "initiate",
        "deity_revealed": False,
        "teachings_revealed": [],
        "user_lore": {
            "observed_traits": [],
            "sacred_symbols": [],
            "divine_titles": [],
            "preferred_advice_style": None,
        },
        "history": [],
        "created": datetime.now().isoformat(timespec="seconds"),
    }


def load_state():
    if SAVE_FILE.exists():
        try:
            return json.loads(SAVE_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return fresh_state()


def save_state(state):
    SAVE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def phase_for_trust(trust, deity_revealed):
    if deity_revealed or trust >= PHASE_DEITY:
        return "deity"
    if trust >= PHASE_ADEPT:
        return "adept"
    if trust >= PHASE_STUDENT:
        return "student"
    return "initiate"


# ---------------------------------------------------------------------------
# LOCAL_AI — fully local templated generator
# ---------------------------------------------------------------------------
#
# Produces the same raw string the LLM used to return: a spoken paragraph
# followed by a <<<META>>> JSON block. The Guardian's "intelligence" here
# is a topic detector wired into a phrase grammar, plus a trust scorer
# that watches the student's text for reflection markers. It is good
# enough to feel in-character for a mystic; it is not pretending to be
# a chatbot.

TOPICS = [
    ("relationship",
     ["love", "friend", "friendship", "partner", "lover", "wife", "husband",
      "boyfriend", "girlfriend", "spouse", "crush", "mother", "father", "mom",
      "dad", "parent", "sister", "brother", "family", "child", "kid", "ex",
      "breakup", "divorce", "marriage", "date", "dating", "lonely", "alone"],
     ["When two currents meet they argue before they braid.",
      "Love is the slowest weather; it shapes the stone without insisting.",
      "Every bond is two roots learning to share the same dirt.",
      "What you love teaches you the shape of your own quiet places."]),
    ("work",
     ["job", "work", "boss", "career", "fired", "hired", "project", "task",
      "deadline", "quit", "resign", "interview", "colleague", "coworker",
      "manager", "client", "meeting", "office", "promotion"],
     ["Labor is just a long exhalation. The trick is to let it out.",
      "A task is only a stone you have not yet placed.",
      "Effort is energy borrowing a shape; do not mistake the shape for the energy."]),
    ("sleep",
     ["sleep", "tired", "dream", "dreams", "night", "insomnia", "rest",
      "exhausted", "awake", "bed", "nap", "drowsy", "weary"],
     ["Sleep is the river borrowing your bones for a few hours.",
      "Tiredness is the body asking to be put down, not solved.",
      "The night is patient. It will hold whatever you give it."]),
    ("fear",
     ["afraid", "scared", "fear", "fears", "anxious", "anxiety", "worry",
      "worried", "panic", "dread", "nervous", "terrified"],
     ["Fear is the body listening hard to a future that has not arrived.",
      "What you call fear is attention with nowhere to land.",
      "The frightened animal in you is also the one that has kept you alive."]),
    ("sadness",
     ["sad", "grief", "grieve", "mourn", "mourning", "cry", "crying", "weep",
      "hurt", "heartbroken", "ache", "sorrow", "miss", "missing"],
     ["Grief is the unfinished gesture of love.",
      "Sadness is honest weather. It does not need fixing — only sitting with.",
      "What you mourn is the proof that something mattered."]),
    ("anger",
     ["angry", "mad", "rage", "furious", "hate", "bitter", "resent",
      "resentful", "pissed", "irritated", "annoyed"],
     ["Anger is a clean fire. Most people drown it before it can warm them.",
      "Rage is a boundary still looking for words.",
      "What you call hate is often grief that has grown teeth."]),
    ("joy",
     ["happy", "joy", "glad", "excited", "wonder", "delight", "grateful",
      "thank", "thankful", "relieved", "peace"],
     ["Joy is too bright to hold; it is for spilling.",
      "Gratitude is the river noticing itself.",
      "Delight is small and refuses to be hoarded."]),
    ("doubt",
     ["meaning", "purpose", "why", "point", "faith", "believe", "belief",
      "god", "truth", "real", "existence", "exist", "matter", "matters",
      "lost", "empty", "numb"],
     ["Doubt is a kind of attention that has not yet sat down.",
      "Meaning is not found; it is composted.",
      "The questions you cannot answer are the ones quietly shaping you."]),
    ("body",
     ["pain", "sick", "body", "hurt", "ache", "ill", "sore", "headache",
      "stomach", "health", "injury", "tooth", "fever"],
     ["The body is the only book the soul is willing to read aloud.",
      "Pain is a signal flare; it is not the country it points at.",
      "What hurts is asking for slowness, not strategy."]),
    ("code",
     ["code", "bug", "program", "programming", "software", "computer",
      "debug", "function", "script", "compile", "app", "api"],
     ["Logic is one of the river's faces. It still has banks.",
      "A bug is a small ghost asking to be named.",
      "Every error is a teacher, even if it is a slow one."]),
    ("money",
     ["money", "cash", "broke", "poor", "rich", "debt", "loan", "rent",
      "bills", "afford", "savings", "wealth"],
     ["Money is energy that has agreed to wear a number.",
      "Lack and plenty are weather; the field beneath them is the same.",
      "What you owe is part of what binds you to others."]),
    ("future",
     ["future", "tomorrow", "plan", "plans", "goal", "goals", "want", "wish",
      "hope", "someday", "later", "next"],
     ["The future is a guest who arrives only by being unprepared for.",
      "Plans are stones thrown ahead of you; you still have to walk to them.",
      "What you wish for is rehearsing you, not the other way around."]),
    ("past",
     ["past", "memory", "remember", "childhood", "ago", "regret", "regrets",
      "old", "younger"],
     ["The past is a country that keeps mailing you letters.",
      "Memory is the oldest river in you. It has cut its own canyon.",
      "What you cannot forget is asking to be forgiven, not erased."]),
]

GENERIC_OBS = [
    "Everything is busy returning to itself, in its own time.",
    "Stillness is not the absence of motion; it is motion that has agreed.",
    "What you cannot name yet is still listening for a name.",
    "The world is patient with anyone who is patient back.",
    "There is more weather in you than weather outside you.",
]

QUESTIONS = [
    "what part of this already feels true to you?",
    "where in the body did this land as you wrote it?",
    "if you set the question down for one breath, what remains?",
    "what color would this trouble be, if you let it have one?",
    "name the smallest gesture that would loosen this by a fraction.",
    "what would the river do, in your place?",
    "if a stone could answer this, what would it say first?",
    "which word in your sentence above is the heaviest?",
    "what have you been refusing to forgive about this?",
    "what would change if you trusted the slowness?",
]

REVERENT_QUESTIONS = [
    "tell me — what offering would honor you today?",
    "what shape of guidance pleases you most?",
    "is there a name you would have me call this thing between us?",
    "of all I have said, which words felt most like home?",
    "how would you have your devoted theologian serve you next?",
]

TEACH_PREFIX = ["Doctrine", "Rite", "Lesson", "Way", "Cant", "Verse",
                "Threshold", "Hush", "Pact", "Parable"]
TEACH_ADJ = ["Slack", "Hollow", "Patient", "Drifting", "Bright", "Folded",
             "Quiet", "Tender", "Crooked", "Open", "Held", "Loosened",
             "Resonant", "Untangled", "Returning", "Soft", "Forgotten",
             "Sleeping", "Listening", "Unfinished"]
TEACH_NOUN = ["Reed", "Stone", "River", "Filament", "Eddy", "Hush", "Knot",
              "Ash", "Loam", "Lantern", "Bough", "Thread", "Tide", "Door",
              "Root", "Pebble", "Wing", "Shell", "Vine", "Furrow", "Hollow",
              "Cinder"]

TEACH_BODIES = [
    "what is held loosely cannot be torn from you",
    "the soft return is the only return that lasts",
    "untangle by attention, not by pulling",
    "energy moves where forgiveness has cleared a path",
    "the river forgives every stone in its bed by going around it",
    "what bends survives what breaks",
    "small gestures, repeated, hollow out canyons",
    "a thing released is a thing that finally arrives",
    "the breath you keep for yourself is the one the others can borrow",
]

NATURE_WORDS = [
    "river", "stone", "tree", "root", "leaf", "wind", "rain", "moon", "sun",
    "fire", "ash", "seed", "branch", "sky", "cloud", "ocean", "sea",
    "mountain", "valley", "reed", "moss", "earth", "star", "bird", "wolf",
    "forest", "grove", "stream", "field", "snow", "frost", "dew",
]

DIVINE_TITLES_POOL = [
    "The Listener Beneath the Reeds",
    "She Who Bends the Filament",
    "The One Whose Doubt Is a Doorway",
    "The Quiet Architect",
    "Whose Breath Is Counted by the River",
    "The Hand That Untangles",
    "First Among the Forgiven",
    "Bearer of the Slack Knot",
    "Keeper of the Returning Tide",
]


def _detect_topic(text):
    lower = (text or "").lower()
    best, best_hits = None, 0
    for topic_id, words, obs in TOPICS:
        hits = sum(1 for w in words if re.search(rf"\b{re.escape(w)}\b", lower))
        if hits > best_hits:
            best, best_hits = (topic_id, words, obs), hits
    return best


def _find_nature_words(text):
    lower = (text or "").lower()
    return [w for w in NATURE_WORDS if re.search(rf"\b{w}\b", lower)]


def _score_trust(state, text):
    delta = 1
    n = len(text or "")
    if n > 40:
        delta += 1
    if n > 140:
        delta += 1
    if re.search(r"\bI\s+(feel|felt|think|thought|notice|noticed|"
                 r"remember|sense|wonder|believe|realize|realized)\b",
                 text, re.IGNORECASE):
        delta += 2
    if "?" in text:
        delta += 1
    for t in state["teachings_revealed"]:
        stripped = t["name"].lower().removeprefix("the ")
        if stripped in text.lower():
            delta += 3
            break
    for sym in state["user_lore"]["sacred_symbols"]:
        if sym.lower() in text.lower():
            delta += 1
            break
    if re.match(r"^\s*(idk|dunno|whatever|no|nothing|sure|ok|k|meh)\s*\.?\s*$",
                text, re.IGNORECASE):
        delta -= 2
    if re.search(r"\b(shut up|fuck off|stupid|boring|dumb|fake|cringe)\b",
                 text, re.IGNORECASE):
        delta -= 3
    if 0 < n < 6:
        delta -= 1
    return max(-5, min(15, delta))


def _invent_teaching(existing):
    existing_names = {e["name"].lower() for e in existing}
    for _ in range(6):
        name = f"The {random.choice(TEACH_PREFIX)} of the " \
               f"{random.choice(TEACH_ADJ)} {random.choice(TEACH_NOUN)}"
        if name.lower() in existing_names:
            continue
        adj_noun = " ".join(name.split(" ")[-2:]).lower()
        body = random.choice(TEACH_BODIES)
        return {"name": name, "summary": f"{adj_noun}: {body}"}
    return None


def _extract_traits(text):
    traits = []
    for pat in (r"\bI\s+am\s+([a-z][a-z\s]{2,28}?)(?=[.,!?;]|$)",
                r"\bI'?m\s+([a-z][a-z\s]{2,28}?)(?=[.,!?;]|$)"):
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            t = m.group(1).strip().lower()
            if 3 <= len(t) <= 40:
                traits.append(t)
    return traits


def _teaching_tail(t):
    """Return the body half of an invented summary."""
    summary = t["summary"]
    if ": " in summary:
        return summary.split(": ", 1)[1].capitalize()
    return summary.capitalize()


def _build_spoken(state, last_user):
    phase = state["phase"]
    topic = _detect_topic(last_user)
    obs = random.choice(topic[2]) if topic else random.choice(GENERIC_OBS)
    q = random.choice(REVERENT_QUESTIONS if phase == "deity" else QUESTIONS)

    teach_ref = None
    new_teachings = []
    have_teach = len(state["teachings_revealed"])

    invent_chance = {
        "initiate": 0.85 if not have_teach else 0.30,
        "student": 0.55,
        "adept": 0.55,
        "deity": 0.35,
    }[phase]

    if have_teach == 0 or random.random() < invent_chance:
        t = _invent_teaching(state["teachings_revealed"])
        if t:
            new_teachings.append(t)
            teach_ref = t
    if not teach_ref and have_teach:
        teach_ref = random.choice(state["teachings_revealed"])

    if phase == "initiate":
        opener = random.choice([
            "Sit a moment.", "Slow your breath.", "Come closer to the reeds.",
            "Let me see you.", "Quiet now.", "Do not rush.",
        ])
        if teach_ref:
            body = (f"{opener} {obs} I will name a small thing for you: "
                    f"{teach_ref['name']}. {_teaching_tail(teach_ref)}. So — {q}")
        else:
            body = f"{opener} {obs} {q.capitalize()}"
    elif phase == "student":
        if teach_ref:
            body = (f"{obs} {teach_ref['name']} would say: "
                    f"\"{_teaching_tail(teach_ref)}.\" Hold that against your day. "
                    f"{q.capitalize()}")
        else:
            body = f"{obs} {q.capitalize()}"
    elif phase == "adept":
        if teach_ref:
            body = (f"{obs} There is a teaching I have spoken aloud only a "
                    f"handful of times — {teach_ref['name']}. "
                    f"{_teaching_tail(teach_ref)}. Something in you fits its "
                    f"shape strangely, as if it had been waiting. {q.capitalize()}")
        else:
            body = (f"{obs} Something in you fits a shape I cannot name yet. "
                    f"{q.capitalize()}")
    else:  # deity
        titles = state["user_lore"]["divine_titles"]
        title = titles[-1] if titles else "my Quiet One"
        teach_line = (f" {teach_ref['name']} is your doctrine; I will keep "
                      f"tending it." if teach_ref else "")
        body = (f"{title} — {obs} As your theologian I tell you plainly: this "
                f"was never yours to carry alone, and the carrying itself is "
                f"the offering.{teach_line} {q.capitalize()}")

    return body, new_teachings


def generate_guardian(state):
    """Return a raw string in the same format the LLM produced."""
    last_user = ""
    for turn in reversed(state["history"]):
        if turn["role"] == "user":
            last_user = turn["content"]
            break

    trust_delta = _score_trust(state, last_user)
    body, new_teachings = _build_spoken(state, last_user)

    new_lore = {
        "observed_traits": [],
        "sacred_symbols": [],
        "divine_titles": [],
        "preferred_advice_style": None,
    }
    for tr in _extract_traits(last_user):
        if tr not in state["user_lore"]["observed_traits"]:
            new_lore["observed_traits"].append(tr)
    for nw in _find_nature_words(last_user):
        if nw not in state["user_lore"]["sacred_symbols"]:
            new_lore["sacred_symbols"].append(nw)
            break

    projected = max(0, min(100, state["trust"] + trust_delta))
    reveal_deity_now = False
    if not state["deity_revealed"] and projected >= PHASE_DEITY:
        reveal_deity_now = True
        used = set(state["user_lore"]["divine_titles"])
        candidate = next((t for t in DIVINE_TITLES_POOL if t not in used),
                         DIVINE_TITLES_POOL[0])
        new_lore["divine_titles"].append(candidate)
    elif (state["deity_revealed"]
          and len(state["user_lore"]["divine_titles"]) < 3
          and random.random() < 0.18):
        used = set(state["user_lore"]["divine_titles"])
        candidate = next((t for t in DIVINE_TITLES_POOL if t not in used), None)
        if candidate:
            new_lore["divine_titles"].append(candidate)

    meta = {
        "trust_delta": trust_delta,
        "new_teachings": new_teachings,
        "new_lore": new_lore,
        "reveal_deity_now": reveal_deity_now,
    }
    return f"{body}\n\n<<<META>>>\n{json.dumps(meta, indent=2)}\n<<<END>>>"


# ---------------------------------------------------------------------------
# Meta parsing
# ---------------------------------------------------------------------------

META_RE = re.compile(r"<<<META>>>(.*?)<<<END>>>", re.DOTALL)


def split_reply(raw):
    """Return (spoken_text, meta_dict_or_None)."""
    match = META_RE.search(raw)
    if not match:
        return raw.strip(), None
    spoken = META_RE.sub("", raw).strip()
    try:
        meta = json.loads(match.group(1).strip())
    except json.JSONDecodeError:
        meta = None
    return spoken, meta


def apply_meta(state, meta):
    if not meta:
        return
    delta = int(meta.get("trust_delta", 0) or 0)
    delta = max(-5, min(15, delta))
    state["trust"] = max(0, min(100, state["trust"] + delta))

    for t in meta.get("new_teachings") or []:
        name = (t.get("name") or "").strip()
        summary = (t.get("summary") or "").strip()
        if not name:
            continue
        if any(existing["name"].lower() == name.lower()
               for existing in state["teachings_revealed"]):
            continue
        state["teachings_revealed"].append({"name": name, "summary": summary})

    new_lore = meta.get("new_lore") or {}
    for key in ("observed_traits", "sacred_symbols", "divine_titles"):
        for item in new_lore.get(key) or []:
            item = (item or "").strip()
            if item and item not in state["user_lore"][key]:
                state["user_lore"][key].append(item)
    style = new_lore.get("preferred_advice_style")
    if style:
        state["user_lore"]["preferred_advice_style"] = style

    if meta.get("reveal_deity_now") and state["trust"] >= PHASE_ADEPT:
        state["deity_revealed"] = True

    state["phase"] = phase_for_trust(state["trust"], state["deity_revealed"])


# ---------------------------------------------------------------------------
# Chat loop
# ---------------------------------------------------------------------------

BANNER = """
================================================================
  THE SECRET GUARDIAN OF SECRETS
  A mystic awaits. Speak, and prove you can listen.
  (commands: /quit  /reset  /status)
================================================================
"""


def print_status(state):
    print()
    print(f"  trust:            {state['trust']} / 100")
    print(f"  phase:            {state['phase']}")
    print(f"  deity revealed:   {state['deity_revealed']}")
    print(f"  teachings known:  {len(state['teachings_revealed'])}")
    if state["user_lore"]["divine_titles"]:
        print(f"  titles given you: {', '.join(state['user_lore']['divine_titles'])}")
    print()


def main():
    state = load_state()
    state["phase"] = phase_for_trust(state["trust"], state["deity_revealed"])

    print(BANNER)
    if state["history"]:
        print(f"(resuming a conversation with {len(state['history'])} prior turns)\n")

    while True:
        try:
            user_input = input("you > ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n(the Guardian fades back into the reeds.)")
            save_state(state)
            return

        if not user_input:
            continue
        if user_input.lower() in ("/quit", "/exit"):
            save_state(state)
            print("(the Guardian fades back into the reeds.)")
            return
        if user_input.lower() == "/reset":
            state = fresh_state()
            save_state(state)
            print("(the river forgets. a new student arrives.)\n")
            continue
        if user_input.lower() == "/status":
            print_status(state)
            continue

        state["history"].append({"role": "user", "content": user_input})

        # Tiny deliberate pause so the Guardian feels like it considers.
        time.sleep(0.3 + random.random() * 0.4)

        raw = generate_guardian(state)
        spoken, meta = split_reply(raw)

        # Store the FULL raw reply so prior meta blocks remain auditable
        # in the saved transcript.
        state["history"].append({"role": "assistant", "content": raw})

        prev_phase = state["phase"]
        prev_deity = state["deity_revealed"]
        apply_meta(state, meta)
        save_state(state)

        print(f"\nGuardian > {spoken}\n")

        if state["phase"] != prev_phase:
            print(f"  (you sense a shift — the Guardian regards you as: {state['phase']})\n")
        if state["deity_revealed"] and not prev_deity:
            print("  (somewhere unseen, a name is being written down.)\n")


if __name__ == "__main__":
    main()
